<!-- Title: friday fit club -->
<!-- Location: Madison -->
<!-- Date: 6 February 2013 -->
<div class="post">
6 February 2013
<br />
Madison
<div class="title">friday fit club</div>
<br />
<p>Last fall, I received one of the nicest, and simultaneously one of the most back-handed compliments I have received in a long time. It was during Fall League. I was matching up against Vinny that game. The two of us we're running each other all over the field on offense, and refusing to let the other catch the deep-ball on d. At one point, Vinny made an in cut along the sideline. I kept with him until he was too close to the disc to be a threat. At the same time, a less experienced player started running deep along the same sideline. I pulled off of Vinny and poached the lane, spreading out as much as I could (which granted isn't all that much) to take away the deep shot, then bolted back to Vinny as he got the dump on the other end of the field. Play continued, and I ran up and down the field a few more times before somebody eventually scored. When I got to the sideline after the point, Fran came up to me and said "Andy, I would be terrified to play against you if you were in shape."</p>
<p>I would be terrified to play against you if you were in shape. It is incredibly flattering. It says that I can hold my own on the field. It says that even with my shortcomings (mainly my height and lack of a flick huck) I can be a threat on the field. And coming from somebody like Fran, who is constantly working out, it was very reassuring. Yet, at the same time, ouch. <i>If you were in shape</i>. But he was right. I was thinking about it a bunch last fall, and Fran made a good point. I really haven't been in shape since I graduated college. On top of that, the peak of my athletic career was most likely September of 2002 or 2003, when I was playing high school football. I can make excuses about getting older and not having time, but ultimately they're just excuses. I look at some of the ultimate players in Madison who are my age or older, hold down full time jobs, and still work out 3+ times a week. Hell, Pollati probably lost ten pounds last spring and got fast enough to make Udderburn after not playing competitively for a few years. And he is eight years older than me. Or take Corey Flynn. I have never seen somebody work so hard at his job (or on his PhD) - on the order of twelve hours a day, six days a week - and after all that go to the gym.</p>
<p>The only thing keeping me from that, keeping me from truly being in shape, is commitment. I haven't had the commitment lately. And I'm sick of that.</p>
<p>Panya is in the mountains of northern Thailand. The living area is in a valley. There is a food forest that goes up the bottom half of a mountain. As you come to Panya from the main road, there is a large dirt path up along the food forest (this is our fire-break, now cleared out and capable of stopping fires). I have nick-named this firebreak Friday Fit Club, after the notorious group of NOISE players in Madison. (Ironically, Wednesdays is my hill workout, Fridays I usually do sprints.) I've been doing my best to run three times a week. It easy, because afternoon session ends at four, and dinner isn't until six-thirty, so I have two and a half hours to get a workout in. It's not so nice, because its balls hot here and I rarely feel like running after a day of work.</p>
<p>Part of me fears posting this. I don't like to boast about something and then not follow through. And I wonder how long this will last. I have a habit of getting really into something, spending a lot of energy on it for a week, then getting bored and stopping. So will I keep running three times a week for the next two months, or will I get lazy again? Will I stop pushing myself and my conditioning will peak (I already need to alter my workouts to make the harder)? I don't know. But I want to. At the very least, I want to get back to Madison ready to go for the club season. I want to be able to play day two of a tournament and not feel like shit. I want to d up against the 5'10" guy and not have to worry about his vertical game. I want to walk off the field after a marathon point, at noon in the middle of July, and know that my guy never touched the disc because I was able to cover him the entire time. And the only person who can make that happen is me.</p>
</div>