<!-- Title: panya clean -->
<!-- Location: Panya -->
<!-- Date: 25 January 2012 -->
<div class="post">
25 January 2013
<br />
Panya
<div class="title">panya clean</div>
<br />
<p>Well, I've officially given up on being clean and have started to be "Panya clean." This is, in part, due to my decision to stop wearing shoes.</p>
<p>Typically, I don't wear shoes at all when staying at permaculture sites. I don't like shoes, and at places like Panya they're not needed most of the time. When I first got here and we were deconstructing the Sala, there were lots of nails strewn about, so it was dangerous to go barefoot. So I wore flip flops all the time (and only had 2 nails go through them). But we finished deconstructing the old Sala, removing the nails from the wood, and even bought a large magnet to collect nails that were lying on the ground. So I feel safe going around barefoot now. I still wear shoes when working, but as soon as afternoon session is over I take them off. Pretty soon I'll have hardened, darkened skin on the bottom of my feet. This is a sign of success.</P>
<p>But Panya clean goes further than my feet. I'm not going to get the dirt out from under my nails until I leave. I clean them fairly regularly, but it's always there.</p>
<p>I have two sets of clothes here - my working clothes, and my non-work clothes. My working clothes are filthy, but that's to be expected - they're work clothes. Right now they're dirty, and often covered in woodchips of some type. We started laying bricks yesterday, so they'll be covered in mud pretty soon. But my non-work clothes are starting to get dirty as well. They're not dirty, per say, but they're starting to get a layer of dust on them. But they're still too clean to send into town to get washed. Because of the natural building internship, there are 40 people at Panya so we go through the water tanks every day. There is rust in the bottom of the tanks. And because of the time of year, the stream we refill the tanks from is running low. And when the stream runs low, we often kick up the rust at the bottom of the stream. And because of all the rust in the water, it's not practical to wash my clothes at Panya. But I don't mind. That's part of life here. It's nice. I like it.</p>
<p>Other than that, things are going really well. I'm feeling great. My belt fits again for the first time since Christmas. The Sala is going up so fast. We have the entire frame up. We had welders from town come this week, and they welded the perlins to the trusses that will support the roof. Next we'll be putting in walls, windows, and the roof. After that, it's interior work. It's really going fast. And the interns tear through the work. It's great. I'm really enjoying all the carpentry work I'm doing. I haven't done too much 'natural building' yet, it has been mostly carpentry stuff. Although I did lay some earthbags this week. I like earthbag building. I like it a lot more than adobe bricks, but the down side is that you use plastic bags and the plastic stays in the building. If this doesn't make any sense to you, you should research "earthbag building."</p>
<p>I watched a really great documentary last night called "Freedom Ahead." It was made by a couple who visited a number of permaculture sites around the world and talked about what freedom means to people. (It was cool to have been to four of the six sites they went to - two in Auroville, Panya, and Pun Pun, the organic farm next to Panya.) I don't have the time to really get into it now, but it challenges the conventional western theory of living a successful life. I'll write more about it later, but for now I highly recommend you buy the movie and watch it.</p>
</div>