<!-- Title: visa run -->
<!-- Location: Burma -->
<!-- Date: 10 February 2013 -->
<div class="post">
10 February 2013
<br />
Burma
<div class="title">visa run</div>
<br />
<p>I went to Myanmar today. Well, more precisely, I went on a visa-run to Myanmar today. What is a visa run? Let me explain. When you enter Thailand, your passport gets stamped allowing you into the country for a certain number of days (the amount of time is determined by the type of visa you have). I have a three-entry, six month visa; meaning that I can enter Thailand three times within six months of when the visa was issued. Each time I enter the country, I am permitted to stay for two months. (It's actually two months, not sixty days. Both times I entered, they stamped the exit date for the same day-of-the-month, not counting that some months have 31 or 28 days.) Due to the large number of tourists spending months at a time in Thailand and the difficulty of obtaining residency for non-citizens, it has become a common practice to leave the country and come back in on the same day to avoid overstaying one's visa.</p>
<p>I first entered Thailand on January 4<sup>th</sup>, and I had until March 4<sup>th</sup> to leave the country. My flight back to the US is not until the first week of April, so I needed to make a visa run sometime during my stay. I will be busy the first week of March (Kelly is coming to visit me), so I figured I would take care of my visa situation today when I was in Chiang Mai. So I got on a minivan bright and early this morning and headed to the border town of Mea Sai.</p>
<p>Mea Sai is on Thailand's northern border. The region is beautiful and mountainous (the tail end of the Himalayan range), but I missed most of it. On the way there, I was consumed with Saul Williams and the last half of <i>Still Life with Woodpecker</i>. On the way back, I was too busy trying to make sure my body kept down the little lunch I has in Mei Sai. (My stomach has been dealing with something this past week, and I thought my body had overcome. Apparently not yet.) To make matters worse, the driver was a mad man. He is the kind of guy who can make "the Kessel Run in less than twelve parsecs." To all of you obnoxiously-nerdy fans who point out that a parsecs is a unit of distance and not time (and who haven't (1) read enough to understand that that is the point or (2) read enough to that people take the long way around the Maw) I say this: precisely! The route from Chiang Mai to Mew Sai is long and windy as it curves about the mountains in the region. In addition to speeding and cutting off others on the road, my driver liked to drive straight through the curves, often entering the oncoming lane to take the shortest route. (Similar to Aaron driving home from High Tide.) Oh what an adventure.</p>
<p>I would like to say that I actually went to Myanmar today, but I didn't really. I went to the Myanmar immigration office, and that was about it. Both countries have made a business out of foreigners making visa-runs. The boarder area is one giant market, filled with locals selling the same jewelry, t-shirts, carved elephants and cigarettes that you can get anywhere and everywhere in the country. After going through immigration in Thailand, I crossed a bridge into Myanmar. Across the bridge I entered the Myanmar immigration office. After stamping my passport, the customs official asked me if I was going to go shopping. I assumed that saying yes would require me to exchange money or some other such process, so I told him no. All I wanted to do was walk around, see if it was any different from Thailand, and then get two more months on my Thai visa. Wrong answer! After telling him no, he stamped my passport again signifying my exit of the country and sent me out. When I left the office, a guard pointed me back towards Thailand because I did not have the proper papers to enter Myanmar. So it goes.</p>
</div>